version: '3'

services:
    db:
        image: postgres:9.6
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: categories_dev
        ports:
            - '5432:5432'
        volumes:
            - ./data:/var/lib/postgresql/data
