version: '3'

services:
    app:
        build:
            context: .
        ports:
            - '4000:4000'
        depends_on:
            - db
        links:
            - db
        command: /bin/sh docker_dev_start.sh
    db:
        image: postgres:9.6
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: categories_dev
        ports:
            - '5432:5432'
        volumes:
            - ~/data:/var/lib/postgresql/data
